require("forvais.plugins.colors")
require("forvais.plugins.harpoon")
require("forvais.plugins.lsp")
require("forvais.plugins.telescope")
require("forvais.plugins.treesitter")
require("forvais.plugins.undotree")
